20181129/codes/ansible_cmdb/ansible_cmdb/urls.py
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('user:login')), name='index'),
    path('user/', include('user.urls')),
    path('host/', include('host.urls')),
]

20181129/codes/ansible_cmdb/host/urls.py
#encoding: utf-8

from django.urls import path

from . import views

app_name = 'host'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete, name='delete'),
]

20181129/codes/ansible_cmdb/user/urls.py
#encoding: utf-8

from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login/', views.login_view, name='login2'),
    path('logout/', views.logout_view, name='logout'),
]

20181129/codes/ansible_cmdb/host/models.py
#encoding: utf-8

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from datetime import timedelta

class Host(models.Model):
    name = models.CharField(verbose_name='主机名', max_length=256, default='', null=False)
    os = models.CharField(verbose_name='操作系统', max_length=256, default='', null=False)
    ip = models.GenericIPAddressField(verbose_name='IP地址')
    arch = models.CharField(verbose_name='架构', max_length=32, default='', null=False)
    mem = models.BigIntegerField(verbose_name='内存', default=0, null=False)
    cpu = models.IntegerField(verbose_name='CPU', default=0, null=False)
    remark = models.TextField(verbose_name='备注', default='', blank=True)
    created_time = models.DateTimeField(verbose_name='发现时间', auto_now_add=True, null=False)
    last_time = models.DateTimeField(verbose_name='最后发现时间', auto_now=True, null=False)

    def is_online(self):
        return timezone.now() - self.last_time < timedelta(hours=6)

    @classmethod
    def create_or_replace(cls, name, ip, arch, os, mem, cpu):
        obj = None
        try:
            obj = Host.objects.get(ip=ip)
        except ObjectDoesNotExist as e:
            obj = Host()
            obj.ip = ip
        obj.name = name
        obj.arch = arch
        obj.os = os
        obj.mem = mem
        obj.cpu = cpu

        obj.save()
        return obj

    def __str__(self):
        return '{0}({1})'.format(self.name, self.ip)

20181129/codes/ansible_cmdb/user/models.py
from django.db import models

# Create your models here.

20181129/codes/ansible_cmdb/host/views.py
#encoding: utf-8

from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Host

@login_required
def index(request):
    return render(request, 'host/index.html', {'objects' : Host.objects.all()})


@login_required
def delete(request):
    pk = request.GET.get("pk", 0)
    Host.objects.filter(pk=pk).delete()
    return redirect(reverse('host:index'))

20181129/codes/ansible_cmdb/user/views.py
#encoding: utf-8

from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout


def login_view(request):
    username = ''
    errors = None
    if 'POST' == request.method:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse('host:index'))

        else:
            errors = ['用户名或密码错误']

    return render(request, 'user/login.html', {'username' : username, 'errors' : errors})


def logout_view(request):
    logout(request)
    return redirect(reverse('user:login'))

20181129/codes/ansible_cmdb/host/templates/host/index.html
{% extends "base.html" %}

{% block title %}主机管理{% endblock %}
{% block expanded_host %}is-expanded{% endblock %}
{% block active_host_cloud %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <table class="table table-bordered table-hover table-sm" id="platform">
                    <thead class="thead-light">
                        <tr>
                            <th>IP(主机名)</th>
                            <th>操作系统</th>
                            <th>配置(CPU/内存)</th>
                            <th>架构</th>
                            <th>发现时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in objects %}
                            <tr>
                                <td>
                                    <i class="fa fa-circle" data-toggle="tooltip" title="最后时间: {{ object.last_time|date:'Y-m-d H:i:s' }}"
                                        {% if object.is_online %}
                                            style="color:green;"
                                        {% else %}
                                            style="color:red;"
                                        {% endif %}
                                    aria-hidden="true"></i>
                                    <a href="javascript:void(0)" data-id="{{ object.id }}">{{ object.ip}}({{ object.name }})</a>
                                </td>
                                <td>{{ object.os }}</td>
                                <td>{{ object.cpu }} 核 / {{ object.mem }} MB</td>
                                <td>{{ object.arch }}</td>
                                <td>{{ object.created_time|date:'Y-m-d H:i:s' }}</td>
                                <td>
                                    <a class="btn btn-sm btn-danger btn-delete" role="button" data-id="{{ object.id }}" data-name="{{ object.ip}}({{ object.name }})" data-toggle="tooltip" title="删除"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr><td colspan="6">暂无数据</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
jQuery(document).ready(function() {
    jQuery('a.btn-delete').on('click', function() {
        var id = jQuery(this).data("id"), name= jQuery(this).data("name");
        if(confirm("确认删除主机记录:" + name)) {
            window.location.replace("{% url 'host:delete' %}?pk=" + id);
        }
    });
});
{% endblock %}

20181129/codes/ansible_cmdb/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{% block title %}主机管理系统{% endblock %}</title>

        <link href="{% static 'plugins/bootstrap-4.1.3/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'plugins/vali-admin/css/main.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'plugins/DataTables-1.10.18/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
        {% block links %} {% endblock %}
        <style type="text/css">
            {% block style %}{% endblock %}
        </style>
    </head>
    <body class="app sidebar-mini rtl sidenav-toggled">
        <header class="app-header">
            <a class="app-header__logo" href="javascript:void(0);">CMDB</a>
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <ul class="app-nav">
                <nav class="navbar navbar-light">
                    <span class="navbar-text" style="font-weight: bolder;">
                        当前登陆用户: {{ request.user.username }}
                    </span>
                </nav>
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu">
                        <i class="fa fa-user fa-lg"></i>
                    </a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="page-user.html">
                                <i class="fa fa-user fa-lg"></i>修改密码
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'user:logout' %}">
                                <i class="fa fa-sign-out fa-lg"></i>退出登录
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <ul class="app-menu">
                <li>
                    <a class="app-menu__item {% block active_host %}{% endblock %}" href="{% url 'host:index' %}">
                        <i class="app-menu__icon fa fa-laptop"></i>
                        <span class="app-menu__label">主机管理</span>
                    </a>
                </li>
            </ul>
        </aside>
        <main class="app-content">
            {% block content %}{% endblock %}
        </main>
        {% block dialogs %}{% endblock %}
        <script type="text/javascript" src="{% static 'plugins/jquery-3.3.1/jquery-3.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/popper.js-1.14.4/umd/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-4.1.3/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/vali-admin/js/main.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/pace-1.0.0/pace.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/DataTables-1.10.18/js/jquery.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/DataTables-1.10.18/js/dataTables.bootstrap4.min.js' %}"></script>
        {% block scripts %}{% endblock %}
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery.extend(jQuery.fn.dataTable.defaults, {
                    language: {
                        url: "{% static 'json/datatable_zh_CN.json' %}"
                    }
                });

                {% block js %}{% endblock %}
            });

        </script>
    </body>
</html>

20181129/codes/ansible_cmdb/user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="">

        <title>主机管理系统</title>
        <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'plugins/vali-admin/css/main.css' %}"  rel="stylesheet" type="text/css" href="css/main.css">
        <style type="text/css">
            div.field-errors > p.text-danger {
                margin: -8px 0px 8px 0px;
                font-size: 10px;
                font-weight: bolder;
            }
        </style>
    </head>
    <body>
        <section class="material-half-bg">
            <div class="cover"></div>
        </section>
        <section class="login-content">
            <div class="logo">
                <h1>CMDB</h1>
            </div>
            <div class="login-box">
                <form class="login-form" action="{% url 'user:login' %}" method="POST" novalidate="novalidate">
                    <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>用户登录</h3>
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">用户名</label>
                        <input class="form-control" type="text" placeholder="用户名" name="username" value="{{ username }}" autofocus="autofocus" />
                    </div>
                    <div class="form-group">
                        <label class="control-label">密码</label>
                        <input class="form-control" type="password" placeholder="密码" name="password" value="">
                    </div>
                    {% if errors  %}
                        <div class="field-errors">
                            {% for error in errors %}
                                <p class="text-danger">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div class="form-group btn-container">
                        <button class="btn btn-primary btn-block"><i class="fa fa-sign-in fa-lg fa-fw"></i>登陆</button>
                    </div>
                </form>
            </div>
        </section>

        <script type="text/javascript" src="{% static 'plugins/jquery-3.3.1/jquery-3.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/popper.js-1.14.4/umd/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-4.1.3/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/vali-admin/js/main.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/pace-1.0.0/pace.min.js' %}"></script>
        <script type="text/javascript">
            jQuery('.login-content [data-toggle="flip"]').click(function() {
                jQuery('.login-box').toggleClass('flipped');
                return false;
            });
        </script>
    </body>
</html>